version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
- url: /fonts
  static_dir: fonts
- url: /img
  static_dir: img

- url: /.*
  script: reviewr.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest